package client;

import java.io.IOException;
import java.io.PrintWriter;
import java.net.Socket;
import java.net.UnknownHostException;

/**
*
* @author Adam Pine, GUI written with NetBeans
*/
public class ClientGUI extends javax.swing.JFrame {
	//The ClientGUI requires a reference to the Client, so that it can call the run method when needed.
	private Client cli;

   /**
    * Creates new form NewJFrame
    * Pass in the Client object so that the send button can reference it,
    * in order to update the variables that are used for sending the HTTP request.
    */
   public ClientGUI(Client cli) {
       initComponents();
       this.cli = cli;
   }

   /**
    * Generated by Netbeans, This sets up all the components for the GUI.
    */
   private void initComponents() {

       txtAddress = new javax.swing.JTextField();
       txtDirectory = new javax.swing.JTextField();
       jLabel1 = new javax.swing.JLabel();
       jLabel2 = new javax.swing.JLabel();
       txtFile = new javax.swing.JTextField();
       btnSend = new javax.swing.JButton();
       jScrollPane1 = new javax.swing.JScrollPane();
       txtAreaLog = new javax.swing.JTextArea();
       jLabel4 = new javax.swing.JLabel();

       setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

       txtAddress.setText("127.0.0.1");

       jLabel1.setLabelFor(txtAddress);
       jLabel1.setText("Address");

       jLabel2.setLabelFor(txtDirectory);
       jLabel2.setText("Directory");

       btnSend.setText("Send");
       btnSend.addMouseListener(new java.awt.event.MouseAdapter() {
           public void mouseClicked(java.awt.event.MouseEvent evt) {
               try {
				btnSendMouseClicked(evt);
			} catch (IOException e) {
				e.printStackTrace();
			}
           }
       });

       txtAreaLog.setEditable(false);
       txtAreaLog.setColumns(20);
       txtAreaLog.setRows(5);
       jScrollPane1.setViewportView(txtAreaLog);

       jLabel4.setLabelFor(txtFile);
       jLabel4.setText("File");

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(layout.createSequentialGroup()
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(jLabel1))
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(txtDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(jLabel2))
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(jLabel4)
                           .addComponent(txtFile, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 250, Short.MAX_VALUE)
                       .addComponent(btnSend)
                       .addGap(20, 20, 20))
                   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                       .addComponent(jScrollPane1)
                       .addContainerGap())))
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jLabel1)
                   .addComponent(jLabel2)
                   .addComponent(jLabel4))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(txtDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(txtFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(btnSend))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
               .addContainerGap())
       );

       pack();
   }                                                     
   
   /**
    * Set the variables of the client object to the current text values.
    * Then tell the client the run, and attempt to get a response from the server.
    * @param evt
    * @throws UnknownHostException
    * @throws IOException
    */
   private void btnSendMouseClicked(java.awt.event.MouseEvent evt) throws UnknownHostException, IOException {                                     
	   cli.address = txtAddress.getText();
	   cli.directory = txtDirectory.getText();
	   cli.file = txtFile.getText();
	   
	   cli.run();
   }                                       

   // Variables declaration - do not modify                     
   public javax.swing.JButton btnSend;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JScrollPane jScrollPane1;
   public javax.swing.JTextField txtAddress;
   public javax.swing.JTextArea txtAreaLog;
   public javax.swing.JTextField txtDirectory;
   public javax.swing.JTextField txtFile;
   // End of variables declaration                   
}
